name: Release Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools_scm python-semantic-release

    - name: Checkout or create release branch
      run: |
        git fetch origin
        git checkout -b release origin/release || git checkout release
        git merge master

    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        semantic-release publish

    - name: Push changes to release branch
      run: |
        git push origin release --tags

    - name: Build package
      run: |
        python -m build

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
