name: Release and Publish Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true  # Ensure all tags are fetched

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine python-semantic-release

    - name: Run semantic-release to create tag and release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: semantic-release publish

    - name: Fetch latest tags
      run: git fetch --tags

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
