name: Retrieve and Use Local Version

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools_scm python-semantic-release

    - name: Run semantic-release to determine version and create tag
      id: determine_version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(semantic-release version)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Determined version: $VERSION"
        git tag $VERSION
        git push origin $VERSION

    - name: Build package with semantic version
      run: |
        python setup.py sdist bdist_wheel

    - name: Rename dist files with semantic version
      run: |
        for file in dist/*; do
          mv "$file" "${file/.tar.gz/-$VERSION.tar.gz}"
          mv "$file" "${file/.whl/-$VERSION.whl}"
        done

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
