name: Upload Python Package
on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types: [created]
permissions:
  contents: write
  id-token: write
  actions: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools-scm build twine
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v8.7.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/*
